name: Build
on:
  push:
  pull_request:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with: 
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: '1.10.0'
          preCommands: |
            echo "**PreCommands Start**"
            echo "${{ secrets.CF_AWS_ACCESSID }}" | wrangler secret put CF_AWS_ACCESSID
            echo "${{ secrets.CF_AWS_SECRET_KEY }}" | wrangler secret put CF_AWS_SECRET_KEY
            echo "${{ secrets.CF_AWS_REGION }}" | wrangler secret put CF_AWS_REGION
            echo "**PreCommands End**"
        env:
          CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}
