name: Build
on:
  push:
  pull_request:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with: 
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: '1.10.0'
        env:
          CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}
          CF_ZONE_ID : ${{secrets.CF_ZONE_ID}}
